# Generated by Django 3.1 on 2021-01-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.proposal')),
            ],
            bases=('projects.proposal',),
        ),
        migrations.CreateModel(
            name='GoalComplete',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.proposal')),
            ],
            bases=('projects.proposal',),
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.proposal')),
            ],
            bases=('projects.proposal',),
        ),
        migrations.CreateModel(
            name='RoleUpdate',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.proposal')),
            ],
            bases=('projects.proposal',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.proposal')),
            ],
            bases=('projects.proposal',),
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('proposal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.proposal')),
            ],
            bases=('projects.proposal',),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
