# Generated by Django 3.1 on 2020-12-29 05:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201228_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-search_ordering']},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=101),
        ),
        migrations.AddField(
            model_name='user',
            name='search_ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='pfp/default.png', upload_to=accounts.models.upload_dest),
        ),
    ]
