# Generated by Django 3.1 on 2021-01-09 08:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201229_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crypto_public_key',
            field=models.CharField(blank=True, default=None, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_in_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='pfp/default.png', upload_to=accounts.models.upload_dest),
        ),
    ]
